apiVersion: v1
appVersion: "4.2.12"
description: Mongoose chart with Pravega storage driver and additional specfic params.
name: mongoose
version: 0.1.4
home: https://github.com/emc-mongoose/mongoose
