apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.entryNode.service.name }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.serviceAccount }}
  serviceAccountName: {{ .Values.serviceAccount }}
  {{- end }}
  ports:
    - name: data
      port: 1099
      targetPort: {{ .Values.dataPort }}
    - name: http
      port: 9999
      targetPort: {{ .Values.httpPort }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ .Values.pod.name }}-0
