apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    name: {{ .Values.service.name }}
spec:
  {{- if .Values.serviceAccount }}
  serviceAccountName: {{ .Values.serviceAccount }}
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - name: data
      port: 1099
      targetPort: 1099
    - name: http
      port: 9999
      targetPort: 9999
    {{- if .Values.debug }}
    - name: debug
      port: 5005
      targetPort: 5005
    {{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ .Values.pod.name }}-0
