apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.service.name }}
spec:
  {{- if .Values.serviceAccount }}
  serviceAccountName: {{ .Values.serviceAccount }}
  {{- end }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.service.name }}
  serviceName: {{ .Values.service.name }}
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        name: {{ .Values.service.name }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key:      "app"
                    operator: In
                    values:   [{{ quote .Values.service.name }}]
              topologyKey:    "kubernetes.io/hostname"
      containers:
      - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.service.name }}

        {{- with .Values.resources }}
        resources:
          limits:
            cpu: {{ quote .limits.cpu }}
            memory: {{ quote .limits.memory }}
          requests:
            cpu: {{ quote .requests.cpu }}
            memory: {{ quote .requests.memory }}
        {{- end }}

        args: {{- printf " [" -}}
          {{- printf "\"--run-node\"" -}}
          {{ if (ne $.Values.args "") and (ne $.Values.args nil) }}
            {{- printf "," }}
            {{- .Values.args -}}
          {{ end }}
          {{- printf "]" }}

        ports:
        - containerPort: 1099
        - containerPort: 9999
        - containerPort: 5005
        command: ["/opt/mongoose/entrypoint-debug.sh"]

