# only for debug entry node
{{ if .Values.debug }}
apiVersion: v1
kind: Service
metadata:
  name: mongoose-entry-node-svc
  labels:
    app: {{ .Chart.Name }}
spec:
  {{- if .Values.serviceAccount }}
  serviceAccountName: {{ .Values.serviceAccount }}
  {{- end }}
  ports:
      targetPort: 9999
    - name: debug
      port: 5005
      targetPort: 5005

  selector:
    mongoose-role: entry-node
{{ end }}
