apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
spec:
  containers:
    - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      name: mongoose-container
      args: {{- printf " [\"--load-step-node-addrs=" -}}
            {{- range $index, $e := until (.Values.replicas|int) -}}
              {{- printf "%s-%d.%s" $.Values.service.name $index $.Values.service.name -}}
              {{ if ne (add $e 1) ($.Values.replicas|int) }}
                {{- printf "," -}}
              {{ end }}
            {{- end -}}
            {{- printf "\"" -}}
            {{ if ne $.Values.args "" }}
              {{- printf "," }}
              {{- .Values.args -}}
            {{ end }}
            {{- printf "]" }}

  restartPolicy: OnFailure
