#apiVersion: v1
#kind: Pod
#metadata:
#  name: {{ .Chart.Name }}
#spec:
#  containers:
#    - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
#      imagePullPolicy: {{ .Values.image.pullPolicy }}
#      name: mongoose-container
#      args: {{- printf " [\"--load-step-node-addrs=" -}}
#            {{- range $index, $e := until (.Values.replicas|int) -}}
#              {{- printf "%s-%d.%s" $.Values.service.name $index $.Values.service.name -}}
#              {{ if ne (add $e 1) ($.Values.replicas|int) }}
#                {{- printf "," -}}
#              {{ end }}
#            {{- end -}}
#            {{- printf "\"" -}}
#            {{ if ne $.Values.args "" }}
#              {{- printf "," }}
#              {{- .Values.args -}}
#            {{ end }}
#            {{- printf "]" }}
#
#  restartPolicy: OnFailure
#
#
#---

apiVersion: v1
kind: Pod
metadata:
  name: rest-query
spec:
  containers:
    - name: rest-query-container
      image: radial/busyboxplus:curl
      {{- $tmp := "{load:{step:{node:{addrs:" -}}
#      {{- range $index, $e := until (.Values.replicas|int) -}}
      {{- $tmp1 := (print $tmp "mongoose-node") -}}
#      {{- end -}}
      {{ printf "\n%s" $tmp1 }}
      command:
        - 'sh'
        - '-c'
        - >
          curl -v -X POST  -H "Content-Type:multipart/form-data" -F "defaults=
          {{- .Values.config | toJson | quote -}}
          ;type=application/yaml" http://mongoose-node-0.mongoose-node:9999/run

  restartPolicy: OnFailure
