apiVersion: v1
kind: Pod
metadata:
  name: {{ .Chart.Name }}
spec:
  containers:
    - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      name: mongoose-container
      args: {{ .Values.args }}
  restartPolicy: OnFailure
