apiVersion: v1
kind: Service
metadata:
  name: mongoose-node
  labels:
    app: mongoose-node
spec:
  clusterIP: "None"
  ports:
    - name: data
      port: 1099
      targetPort: 1099
  selector:
    name: mongoose-node