apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.service.name }}
  labels:
    mongoose-role: additional-node
spec:
  {{- if .Values.serviceAccount }}
  serviceAccountName: {{ .Values.serviceAccount }}
  {{- end }}
  {{- $count := ((add (.Values.replicas|int) -1)|int) -}}
  {{ if lt $count 1}}
  replicas: 0
  {{ else }}
  replicas: {{ $count }}
  {{ end }}
  selector:
    matchLabels:
      name: {{ .Values.service.name }}
  serviceName: {{ .Values.service.name }}
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        name: {{ .Values.service.name }}
    spec:
      {{- if .Values.serviceAccount }}
      serviceAccountName: {{ .Values.serviceAccount }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key:      "app"
                    operator: In
                    values:   [{{ quote .Values.service.name }}]
              topologyKey:    "kubernetes.io/hostname"
      containers:
        - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Values.service.name }}
          args: ["--run-node"]

          {{- with .Values.resources }}
          resources:
            limits:
              cpu: {{ quote .limits.cpu }}
              memory: {{ quote .limits.memory }}
            requests:
              cpu: {{ quote .requests.cpu }}
              memory: {{ quote .requests.memory }}
          {{- end }}

          ports:
          - containerPort: 1099
          - containerPort: 9999
          {{ if .Values.debug }}
          - containerPort: 5005
          command: ["/opt/mongoose/entrypoint_debug.sh"]
          {{- end }}
