apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongoose-node
spec:
  replicas: 3
  selector:
    matchLabels:
      name: mongoose-node
  serviceName: mongoose-node
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        name: mongoose-node
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key:      "app"
                    operator: In
                    values:   ["mongoose-node"]
              topologyKey:    "kubernetes.io/hostname"
      containers:
        - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: mongoose-node
          args: ["--run-node"]
          ports:
            - containerPort: 1099