apiVersion: v1
appVersion: "4.2.15"
description: Mongoose is a horizontally scalable and configurable performance testing utility.
name: mongoose
version: 0.1.8
home: https://github.com/emc-mongoose/mongoose
